name: CI

on:
  push:
    branches:
      - '**' # This will run the workflow on every push to any branch

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    outputs:
      images: ${{ steps.build-matrix.outputs.images }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run CI tests for subdomain.domain.tld
      run: make link-ci GATEWAY=gateway-sshd FQDN=subdomain.domain.com

    - name: Run CI tests for app.subdomain.domain.tld
      run: make link-ci GATEWAY=gateway-sshd FQDN=app.subdomain.domain.com

    - name: Prepare release matrix
      id: build-matrix
      run: |
        awk '/build/ { split($(NF-1), a, "/"); split(a[2], b, ":"); 
          printf "{\"repository\": \"%s\", \"image\": \"%s\", \"tag\": \"%s\", \"path\": \"%s\"}\n", 
          a[1], b[1], b[2], $NF }' Makefile \
        | jq -crs '"images=\(.)"' >> $GITHUB_OUTPUT

  build_and_push:
    if: github.ref_name == github.event.repository.default_branch
    needs: build_and_test

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        include: ${{ fromJson(needs.build_and_test.outputs.images) }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Substitute image registry/repository
        run: |
          find . -type f -exec sed -i "s| ${{ matrix.repository }}/| ghcr.io/${{ github.repository_owner }}/|g" {} +

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/${{ matrix.image }}
          tags: type=raw,value=${{ matrix.tag }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.path }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
